### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by matsair** [Webhose/webhoseio-python#1]
Running `pip install webhoseio` in a conda environment (Python 3.6) gives me this error:

```
Collecting webhoseio
  Using cached webhoseio-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c_/7qt1bc0j1hj7f54sflrlkl000000gt/T/pip-build-z4fsj3b2/webhoseio/setup.py", line 8, in <module>
        with open('README.md', 'r', 'utf-8') as f:
      File "/Users/werki001/miniconda3/envs/mt/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c_/7qt1bc0j1hj7f54sflrlkl000000gt/T/pip-build-z4fsj3b2/webhoseio/
```

Any ideas?

**Comment by rangeva** [comment]
Did you use sudo?

`sudo pip install webhoseio`

**Comment by matsair** [comment]
I did, but that also didn't work:
```
Collecting webhoseio
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103834a90>: Failed to establish a new connection: [Errno 65] No route to host',)': /simple/webhoseio/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103834940>: Failed to establish a new connection: [Errno 65] No route to host',)': /simple/webhoseio/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103834f28>: Failed to establish a new connection: [Errno 65] No route to host',)': /simple/webhoseio/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103834f60>: Failed to establish a new connection: [Errno 65] No route to host',)': /simple/webhoseio/
```

**Comment by rangeva** [comment]
Interesting... 

Installing from source works?

> $ git clone https://github.com/Webhose/webhoseio-python
> $ cd webhoseio-python
> $ python setup.py install

**Comment by matsair** [comment]
Yeah, installing from source works.

**Comment by jimr** [comment]
You need to define a `MANIFEST.in` file that includes the `README.md`. See https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template or https://github.com/jimr/Showcase/blob/master/MANIFEST.in for an example. If you didn't reference `README.md` in `setup.py` it wouldn't be a problem.

I use `check-manifest` before uploading to PyPI: https://pypi.python.org/pypi/check-manifest

**Comment by jimr** [comment]
Any chance of bumping the version and releasing to PyPI? It's currently not possible to install v0.4 from PyPI...

**Comment by rangeva** [comment]
Here you go: https://pypi.python.org/pypi/webhoseio

**Comment by jimr** [comment]
Thanks!
